name : First Workflow

# Trigger

on : 
   workflow_dispatch:
   push:


jobs :
     Hello-Job:
          runs-on : ubuntu-latest
          steps:
             - name : Hello World
               run : echo "Hello World" 

              # Step 2
             - name : Multi-line bash
               run : | # for Multi-line commands
                  echo "I am"
                  echo "a multi-line"
                  echo "script".

     echo-goodbye:
          needs: Hello-Job # Sequential running of jobs
          runs-on : ubuntu-slim
          
          steps:
            - name : Say GoodBye
              run : echo "GoodBye"
            - name : Event Name 
              run : |
               echo "Event name: ${{github.event_name}}" # Context Variable

     windows-echo:
      if: github.event_name == 'push'
      runs-on : windows-latest
      steps:
        - name : Show OS
          shell : bash
          run :  echo " the job is running o a Windows runner"
             
              
             

    


    
